-- Migration to add performance indexes for slower queries
-- Generated by Antigravity on 2026-01-17

-- Social Posts indexes
CREATE INDEX IF NOT EXISTS idx_social_posts_scheduled_date ON public.social_posts (scheduled_date);
CREATE INDEX IF NOT EXISTS idx_social_posts_profile_id ON public.social_posts (profile_id);

-- Funnels indexes
CREATE INDEX IF NOT EXISTS idx_funnels_is_active ON public.funnels (is_active);

-- Tasks indexes
-- Note: 'tasks' table was reported as missing during initial check.
-- Uncomment the following lines if/when the 'tasks' table is created.
-- CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON public.tasks (due_date);
-- CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to_id ON public.tasks (assigned_to_id);
